name: API Client

on:
  workflow_dispatch:
  push:
    branches: [main, stable-*]
    paths:
      - .github/workflows/_python.yml
      - .github/workflows/api-client.yml
      - api-client/**
      - shared/**
      - tools/python*

  pull_request:
    branches: [main, stable-*]
    paths:
      - .github/workflows/_python.yml
      - .github/workflows/api-client.yml
      - api-client/**
      - shared/**
      - tools/python*

  schedule:
    - cron: 0 1 * * 1

jobs:
  python:
    uses: ./.github/workflows/_python.yml
    with:
      context: api-client
