name: Worker

on:
  workflow_dispatch:
  push:
    branches: [main, stable-*]
    paths:
      - .github/workflows/_python.yml
      - .github/workflows/worker.yml
      - worker/**
      - tools/python*

  pull_request:
    branches: [main, stable-*]
    paths:
      - .github/workflows/_python.yml
      - .github/workflows/worker.yml
      - worker/**
      - tools/python*

  schedule:
    - cron: 0 1 * * 1

jobs:
  python:
    uses: ./.github/workflows/_python.yml
    with:
      context: worker
